### ISSUE TITLE
Nothing Rendering

### ISSUE THREAD

**Issue by wjdhamilton** [jxxcarlson/meenylatex#6]
Hello!

As per our previous discussion, #2 , I have tried to render the example using the following: 

```elm
view : Model -> Html Msg
view model =
    let
        macros =
            "\\newcommand{\\bra}{\\langle}"
    in
    div []
        [ img [ src "/logo.svg" ] []
        , h1 [] [ text "Your Elm App is working!" ]
        , MiniLatex.render NoDelay macros "Pythagoras says: $a^2 + b^2 = c^2$"
        ]
```

But it simply produces a blank space as follows:

![Screenshot 2020-01-29 at 09 33 38](https://user-images.githubusercontent.com/7499818/73344585-826f5880-427a-11ea-982c-e61b4d4e1b35.png)

Have I used the wrong macro? 

I use LaTex all the time, for a course I'm doing with the Open University, but I've never had to understand the macro side of it so I'm a bit lost.

**Comment by wjdhamilton** [comment]
Hello! May I politely poke you again?

**Comment by jxxcarlson** [comment]
Please do!!!

**Comment by jxxcarlson** [comment]
I ran you example as in the code below using version 9.0.1 of the package.  It worked for me.  Could you check your `elm.json` for the meenylatex version?

Also, if I don't respond within a day, please contact me on gmail at jxxcarlson.

```
module Main exposing (..)

import Browser
import Html exposing (Html, div, h1, img, text)
import Html.Attributes exposing (src, style)
import MiniLatex
import MiniLatex.Render exposing (MathJaxRenderOption(..))



---- MODEL ----


type alias Model =
    {}


init : ( Model, Cmd Msg )
init =
    ( {}, Cmd.none )



---- UPDATE ----


type Msg
    = NoOp


update : Msg -> Model -> ( Model, Cmd Msg )
update msg model =
    ( model, Cmd.none )



---- VIEW ----


view : Model -> Html Msg
view model =
    let
        macros =
            "\\newcommand{\\bra}{\\langle}"
    in
    div []
        [ img [ src "/logo.svg" ] []
        , h1 [] [ text "Your Elm App is working! (Test)" ]
        , MiniLatex.render NoDelay macros "Pythagoras says: $a^2 + b^2 = c^2$"
        ]

---- PROGRAM ----


main : Program () Model Msg
main =
    Browser.element
        { view = view
        , init = \_ -> init
        , update = update
        , subscriptions = always Sub.none
        }
```

**Comment by jxxcarlson** [comment]
PS.  You may be interested in this: https://jxxcarlson.github.io/app/text-editor/index.html

**Comment by jxxcarlson** [comment]
You may want to use the latest version (10.0.3) and take a look at the section on math-mode-macros in https://demo.minilatex.app/

**Comment by jxxcarlson** [comment]
Am closing this now. Please reopen or contact me if there are problems.
